#!/bin/sh

echo "/etc/Configure: enter" > /dev/kmsg

mount -t proc proc proc
mount -t sysfs sys sys

/sbin/ifconfig lo 127.0.0.1 up

mount -t ramfs ramfs /ramdisk
mkdir -m 777 -p /ramdisk/var \
/ramdisk/var/run \
/ramdisk/var/log \
/ramdisk/tmp \
/ramdisk/tmp/pub \
/ramdisk/optlog \
/ramdisk/smb \
/dev/pts \
/dev/mtd

ln -s ../mtd0 /dev/mtd/0
ln -s mtdblock4 /dev/nandjffs
ln -s mtd4 /dev/jffsmtd
. /etc/scripts/mount_jffs.sh
sonos_mount_jffs >/dev/kmsg 2>&1

mount -t devpts none /dev/pts

/etc/init.d/Srandom

/sbin/insmod /modules/sonos_device.ko
/sbin/insmod /modules/chk.ko
/sbin/insmod /modules/hwevent_queue.ko
/sbin/insmod /modules/audiodev.ko

if [ -f /modules/ir_rcvr.ko ]; then
    /sbin/insmod /modules/ir_rcvr.ko
fi

touch /var/run/sonosledmgrd.flash_booting_led
/sbin/frcheck
frcheck_stat=$?

if [ $frcheck_stat -ne 1 ]; then
  /opt/bin/sonosledmgrd --fr

  if [ $frcheck_stat -eq 0 ]; then
    /wifi/netstartd --hard-reset
  elif [ $frcheck_stat -eq 2 ]; then
    /wifi/netstartd --soft-reset
  fi
fi

mkdir -p /jffs/app/run \
  /jffs/app/log \
  /jffs/app/debug \
  /jffs/app/debug/dsp \
  /jffs/app/settings \
  /jffs/sys/run \
  /jffs/sys/log \
  /jffs/sys/debug \
  /jffs/sys/settings \
  /jffs/net/run \
  /jffs/net/log \
  /jffs/net/debug \
  /jffs/net/settings \
  /jffs/persist

if [ -f /etc/dsmf_setup ]; then
  echo "Running DSMF setup..."
  /etc/dsmf_setup
fi

/bin/mdputil -B

HOSTNAME=Sonos-`/bin/mdputil | /usr/sbin/keyval ^SERIAL | /usr/bin/cut -c 1-12`
/bin/hostname $HOSTNAME

if [ -f /jffs/Configure ]; then
  echo "Running custom Configure..."
  exec /jffs/Configure
fi

echo 262143 > /proc/sys/net/core/rmem_max
echo 0 > /proc/sys/net/ipv4/icmp_echo_ignore_broadcasts

wifiType=N

/sbin/insmod /wifi/$wifiType/adf.ko
/sbin/insmod /wifi/$wifiType/asf.ko
/sbin/insmod /wifi/$wifiType/ath_hal.ko
if [ -f /wifi/$wifiType/dfs.ko ]; then
    /sbin/insmod /wifi/$wifiType/dfs.ko
fi
/sbin/insmod /wifi/$wifiType/ath_driver.ko

/sbin/insmod /wifi/bridge.ko


/usr/sbin/setmac

ifconfig eth0 0.0.0.0

touch /var/run/waitforip

if [ -f /etc/unlocked_build_flag -o -e /jffs/system/Configure.dev ]; then
    ln -s /opt/htdocs_locked /tmp/htdocs_locked

    touch /tmp/device_unlocked_flag
fi

if [ -f /jffs/system/Configure.dev ]; then
    sh /jffs/system/Configure.dev
fi

if [ -s /jffs/hosts ]; then
    touch /jffs/hosts
else
    cp /etc/hosts.orig /jffs/hosts
fi

/etc/init.d/Krandom

echo "Configure script complete."

echo "/etc/Configure: exit" > /dev/kmsg
