#!/bin/sh

#####
# Handler script for sddpd, the Device Discovery Protocol daemon developed
# by Control4. This is meant to be run in perpetuity thanks to the inittab.
# If you must use another technique for SDDP, touch
# /var/run/stopsddp and run `killall sddpd`.
#####

. /etc/rundaemon.sh

trackrestart sddpd /var/run/sddpd.start

# sddpd requires IP and DNS.
waitfordns

waitwhiletrue "[ -f /var/run/stopsddp ]"

sddpd_opts="-n" # don't daemonize

if [ -f /jffs/dev_sddp.conf ]; then
  echo "Found /jffs/dev_sddp.conf; using it instead of default /etc/sddp.conf."
  sddpd_opts="$sddpd_opts -c /jffs/dev_sddp.conf"
fi

exec /sbin/sddpd $sddpd_opts
