# This is a TOML configuration document
#
title = "Anacapa logger configuration"

# SONOS_LOG_EMERGENCY = 0, /**< the system is unusable */
# SONOS_LOG_ALERT = 1, /**< an action must be taken immediately else system is likely to become unusable */
# SONOS_LOG_CRIT  = 2, /**< critical conditions */
# SONOS_LOG_ERR   = 3, /**< error conditions */
# SONOS_LOG_WARN  = 4, /**< warning conditions */
# SONOS_LOG_NOTE  = 5, /**< notify about normal but significant condition */
# SONOS_LOG_INFO  = 6, /**< informational */
# SONOS_LOG_DEBUG = 7, /**< debug */
# SONOS_LOG_DBG_1 = 8, /**< beginning of the extra debug messages range */
# SONOS_LOG_DBG_2 = 9,
# SONOS_LOG_DBG_3 = 10,
# SONOS_LOG_DBG_4 = 11, /**< end of the extra debug messages range */

# Each section defines one log destination
# defaultLevel = -1 means no default logging for this destination
# default backup location: /jffs/app/log

# Main logging for anacapa
[[FILE]]
name = "anacapa.log"
fileSize = 262144
preserveSize = 65536
defaultLevel = 4
backup = true
filter = {}

### additional destinations ###

# Special Logging for direct control
[[FILE]]
name = "anacapa.dc.log"
fileSize = 65536
preserveSize = 16384
defaultLevel = -1
filter = {main=3,muse=6,museauth=6,muse_token_service=6,cloudqueue=6,spot=6,spot_abr=6,spot_q=6,spot_hal=6,cb=6}

# Special Logging for Muse Command and Response Messages
[[FILE]]
name = "anacapa.musecmdandrsp.log"
fileSize = 65336
preserveSize = 60000
defaultLevel = -1
filter = {muselogcmd=7, muselogrsp=7}

# Special Logging for Muse debug statistics
[[FILE]]
name = "anacapa.musedebug.log"
fileSize = 65536
preserveSize = 16384
defaultLevel = -1
filter = {muse_debug=7,museperf=6}

# Special Logging for Muse Event Messages
[[FILE]]
name = "anacapa.museevt.log"
fileSize = 16384
preserveSize = 8192
defaultLevel = -1
filter = {muselogevt=7}

# Special Logging for HomeTheater pipeline
[[FILE]]
name = "anacapa.ht.log"
fileSize = 65536
preserveSize = 16384
defaultLevel = -1
filter = {main=3,tv_proc=6,spdif=6,liblla_input=4,lla_in_tv=4,alsa_in_tv=4,ht_config=5,htaudio=4,mixsat=6,htsat_tx=5,mixgm=6,htmesh_tx=5,autoplay_tv=4,nsd=4,decoderset=5,decoder_pcm=4,ddlic=4,dlbdec=4,dts=4,dlbdap=4,dlbdmx=4,dolbyOAR=4,UDCSubParams=4,udcdecoder=4,timesync=5,tv_asrc=5,tv-proc-as=4,tv-sat-as=4,tv-dm-as=4,tv-hp-as=5}

# Special Logging for Headphones pipeline

# Logging for Headphones messages

# Special Logging for vanished list debugging
[[FILE]]
name = "anacapa.vl.log"
fileSize = 32768
preserveSize = 16384
defaultLevel = -1
filter = {main=3,wake=7}

# Special Logging for anacapa worker telemetry

# Special Logging for trueplay debugging
[[FILE]]
name = "anacapa.trueplay.log"
fileSize = 65536
preserveSize = 16384
defaultLevel = -1
filter = {main=3,piatp_node=7,trueplay=7,trueplay_calibration_manager=9,trueplay_tuning_handler=9,trueplay_channel_config_handler=9,trueplay_dp=7,trueplay_zp=7,auto_trueplay=7,manual_node=7}

# Special Logging for snf
[[FILE]]
name = "anacapa.snf.log"
fileSize = 32768
preserveSize = 16384
defaultLevel = -1
filter = {main=3,advert=6,upnpeventing=6,ana_http=5,arpchecker=6,association=8,assoctracker=6}

# Logging for Alarm Clock Job
[[FILE]]
name = "anacapa.alarm.job.log"
fileSize = 16384
preserveSize = 8196
defaultLevel = -1
filter = {AlarmClock_Schedule=7, AlarmClock_Execute=7}

# Logging for AVT Media Renderer 'performance counter'
[[FILE]]
name = "anacapa.avt.play.log"
fileSize = 65536
preserveSize = 16384
defaultLevel = -1
filter = {avt_play=7}

# Logging for Channel Source state changes
[[FILE]]
name = "anacapa.chsrc.state.log"
fileSize = 8192
preserveSize = 4096
defaultLevel = -1
filter = {chsrc_state_events=7}

# Logging for Channel Source track processor
[[FILE]]
name = "anacapa.chsrc.track.proc.log"
fileSize = 8192
preserveSize = 4096
defaultLevel = -1
filter = {chsrc_track_proc=7}

# Logging for external audio source actions
[[FILE]]
name = "anacapa.ext.audio.action.log"
fileSize = 8192
preserveSize = 4096
defaultLevel = -1
filter = {ext_audio_action=7}

# Logging for GM 'performance counter'
[[FILE]]
name = "anacapa.gm.events.log"
fileSize = 8192
preserveSize = 4096
defaultLevel = -1
filter = {gm_events=7}

# Logging for HW Events
[[FILE]]
name = "anacapa.hw.events.log"
fileSize = 65536
preserveSize = 16384
defaultLevel = -1
filter = {hw_events=7}

# Logging for LeanUI

# Logging for lechmere websocket events
[[FILE]]
name = "anacapa.lechmere.event.log"
fileSize = 8192
preserveSize = 2048
defaultLevel = -1
filter = {websocket_close=7}

# Logging for RC Media Renderer UPNP events
[[FILE]]
name = "anacapa.rc.upnp.log"
fileSize = 65536
preserveSize = 16384
defaultLevel = -1
filter = {rc_upnp_events=7}

# Special logging for logcat
[LOGCAT]
defaultLevel = 4
filter = {}

# Logging for all things Spotify
[[FILE]]
name = "anacapa.spotify.log"
fileSize = 65536
preserveSize = 16384
defaultLevel = -1
filter = {spot=6,spot_abr=6,spot_hal=6,spot_q=6,spotrl=6,spotifyzc=6,SpotZc_Success=7,SpotZc_Failure=7}
