# This is a TOML configuration document
#
title = "Sonos LED Manager server logger configuration"

# SONOS_LOG_EMERGENCY = 0, /**< the system is unusable */
# SONOS_LOG_ALERT = 1, /**< an action must be taken immediately else system is likely to become unusable */
# SONOS_LOG_CRIT  = 2, /**< critical conditions */
# SONOS_LOG_ERR   = 3, /**< error conditions */
# SONOS_LOG_WARN  = 4, /**< warning conditions */
# SONOS_LOG_NOTE  = 5, /**< notify about normal but significant condition */
# SONOS_LOG_INFO  = 6, /**< informational */
# SONOS_LOG_DEBUG = 7, /**< debug */
# SONOS_LOG_DBG_1 = 8, /**< beginning of the extra debug messages range */
# SONOS_LOG_DBG_2 = 9,
# SONOS_LOG_DBG_3 = 10,
# SONOS_LOG_DBG_4 = 11, /**< end of the extra debug messages range */

# Each section defines one log destination
# defaultLevel = -1 means no default logging for this destination

# Main logging
[[FILE]]
name = "sonosledmgrd.log"
fileSize = 262144
preserveSize = 65536
defaultLevel = 4
filter = {ledmgrd=6,LEDManager=6,ledmgr-server=6,leds_zp=6}
