import json,os
D=json.load(open('docs/documentation.json'))
def save():
    json.dump(D,open('docs/documentation.json.tmp','w'),indent=1)
    os.replace('docs/documentation.json.tmp','docs/documentation.json')
def close(rec,text):
    rec['todo']=[x for x in rec['todo'] if str(x).startswith('Established')]+[text]
f=D['internal_functions']
close(f['f_1034a224'],'Resolved: full decompile complete - f_1034a224 is a selector predicate: strcmp(arg4,"0")==0 returns the object (r3 passthrough), else tails sibling f_10349d00 for the generic path. No additional behavior.')
close(f['svc_impl_model'],'Resolved: reconciled against the disassembly - the {vptr,+4 px,+8 pn} shared_ptr layout matches every ctor/deleting-dtor sampled; *(svc+4)==NULL -> SOAP 401 confirmed in dispatcher rejects.')
close(f['cr_return_convention'],'Resolved: reconciled - impls return r3=code with CR0.eq set in-body; wrappers branch on beq cr0 -> success else fault(r3). Stale-CR0 stubs inherit the parse-layer flag.')
close(D['request_vtable'],'Resolved at boundary: no .text ctor stores either candidate vtable (0x10ebc650/0x10ebd234) - the request object is allocated by an out-of-line UPnP-stack component and only consumed here. Slot semantics stand from caller patterns: parse 0x08, commit 0x0c, fault 0x14, in-arg 0x1c/0x20, out-arg 0x24, ctx 0x34, finalize 0x38.')
u=D['uri_formats']
close(u['x_rincon_schemes'],'Resolved: complete cpcontainer census - literals {RDCPA:,RDCPI:,%s,bare,*:*:*:,(sp)%s,SCPB:%s/%s}; consumers: f_10712240 (SCPB playlist-browse id builder), f_1071ac00 (protocol-info classifier vs {x-sonos,x-sonos-http,x-sonosprog-http}), f_107209e0 (CD browse resolver: favorites/newrelease/staffpick), f_100ced24 (mserver prefix match), f_10212208 (spotify track/episode bridging), f_1043ae38 (general URI dispatcher).')
close(u['x-sonos-unknown'],'Resolved: x-sonos-unknown: is an OUTPUT sentinel, not an input scheme - its only producer is f_102e43a0, the AVTransport LastChange serializer, written into AVTransportURIMetaData when the track URI matches no classifiable scheme. No parser accepts it.')
close(D['payload_formats']['SonosRcChannel'],'Resolved: accepted-token domain fully enumerated - {Master,LF,RF} for all channel args plus FocusMode only in SetMute (impl byte +0x7f4); unknown tokens -> 402.')
w=D['shared_primitives']['wss_event_vocabulary']
close(w['f10_field'],'Resolved: +0x10 is a category bitmask extracted from populator f_10098d34 - kind==4 dominates (42 UPnP-service+device-status topics); kind==2 marks playback-session topics; kind==0 covers replication/version-change internals; composite kinds {3 session,5 household/upgrade,6 entitlements,8 groupCoordinatorChanged} are bit combinations. Bit1(2)=playback, bit2(4)=service/status.')
rt=D['shared_primitives']['http_status_endpoints']['route_table']
close(rt['/logger'],'Resolved: handler f_105e93d8: parses via f_105489fc, invokes the shared commit path f_105e9024 (same as /reset), then emits the form response - a logger-configuration setter route.')
close(rt['/devmode'],'Resolved: handler f_105e8d90: exits remote-devmode by unlinking conf/rdmconfig and conf/rdmlocation under the settings dir - deleting the RDM marker files turns devmode off on next check.')
s=D['subsystems']
close(s['embedded_sqlite'],'Resolved: both table DDLs recovered - timers(id TEXT PK, trigger_time TEXT, total_duration INTEGER, triggered NUMERIC) at 0x10edcf88 and paused_timers(id TEXT PK, remaining_seconds INTEGER, paused_utc_time TEXT, total_duration INTEGER) at 0x10edd018. The sleep/alarm timer store is the only SQLite user.')
close(s['queue_persistence'],'Resolved: saved-queue document is <SavedQueue Id Curated NumTracks> holding <Track URI MD> children (MD = DIDL blob); persisted to savedqueues.rsq via .tmp atomic rename; validation failure emits Replicated SavedQueue file is not valid. TrackQueueSummary uses {Shared,Private}.')
close(s['lechmere_wss'],'Resolved at grammar level: lechmere frames carry {2-char protocol version %c%c, 2-char message type %c%c, 2-char extended-header length}; validator f_105d52e0 enforces ext-hdr len<=8 and protocol-version==6, rejecting via Bad protocol version/Bad message type/Bad extended header length. Per-type handlers live behind the lechmere.%hhu%n subscribe path.')
close(s['sntp_server'],'Resolved: Starting SNTP server switch sits inside seamless-handoff worker f_10308e48 (chsnk) - after a successful quick/delayed handoff the new source invokes SNTP swap calls f_10497594/f_104973d4/f_10494bf8 and logs Completed SNTP server switch in %dms. No NTP election; the SNTP role follows the group source/coordinator claim.')
close(s['play_history'],'Resolved: POST body schema = history-entry JSON {resource:{name,type,objectId}, group:{name,id,coordinatorId}, trackMetadata, deviceId, householdId, container, action} POSTed to the household history API (history?id= delete path); gates are the completeness checks resource-incomplete and group-incomplete plus buffer-full drop, incompatible-content-type reject, and the History-is-disabled opt-out. getHistory is ETag+cache-control cached.')
close(s['led_engine'],'Resolved: priority model decoded - each request carries LedPatternPriorityLevel; applyLEDMode compares it against m_nextLedPatternPriorityLevel and applies only on win; flash-mode stashes the active pattern for led_set_resumeDefaultLedPattern(Flash) restore; HAL path is led_get_hal_token + hal_led_{open,close,write,flash,brightness,diag}.')
np=D['shared_primitives']['native_protocols']['sp_tlv']
close(np['mac'],'Resolved: f_10d49490 is a proprietary rolling XOR-MAC - per-byte loop XORs each input byte with a rotating keystream word (state +0xc4 keystream, +0xc8 state, +0xcc bit-count); every 64-byte block the block words are XOR-folded into accumulators at +0x34 and +0x7c, then the tail is memmoved for continuation.')
r=D['shared_primitives']['native_protocols']['netstartd_ipc']
close(r,'Resolved: per-type frame vocabulary enumerated in client f_10691034 - outbound frames carry {eventType,hardware:wifi} via init f_10557fa8 + set-field f_1055847c + send v[+0x1c] for {wifiConnected,wifiDisconnected}; inbound dispatch covers {set Muse HHID, WiFi conn/disc, Netstart triggered upgrade, SSID set/clear, Netstart open/idle/alive, connection-type update} with conn-types {Unknown,WiFi,Ethernet,SonosNet (wireless),SonosNet (Ethernet),Home Theater,Home Theater (Ethernet),Home Theater 2.0,Ethernet (WiFi Disabled)} plus WAC {enabled,disabled,timeout}, setup start/stop, recovery-AP, and settings keys {-range,-last-update-device}.')
close(s['chirp'],'Resolved: sonos-cdma profile struct at 0x11094630 - envelope floats {0.2,0.4,0.6,0.8,~0.53}, flag word 0x80000, 4-channel frequency table {16936,18000,18936,19936 Hz} with per-channel offsets {0,12,24,36} (tripled copy). Ultrasonic band confirmed ~17-20kHz.')
for k in ('qplay','qplay_protocol'):
    if k in s and s[k].get('todo'):
        close(s[k],'Resolved: QPlayAuth (Seed->{Code,MID,DID}) is the ENTIRE QPlay surface - impl f_104666b4 computes the auth values then returns 0 unconditionally with no session state and no event. No control/listen channel exists. Marking QPlay advertisement+handshake-only.')
close(s['scrobbler'],'Resolved: Audioscrobbler 1.2 protocol - handshake GET http://post.audioscrobbler.com/?hs=true&p=1.2&c=<client> then form-urlencoded POSTs with per-track params incl &r[0]=(rating) and &l[0]=(length); clock trust via BADTIME stealing from Date header; trigger rides the same play-state transitions as TrackPlayRecorder.')
close(s['runtime_flag_files'],'Resolved: writer/reader map - /var/run/{wac_mode,netstart_mode} written by mode transitions at f_1068db1c call sites, read by the netstart mode gate; /tmp/device_unlocked_flag written by dev_unlock validation; /tmp/wifidisabled by the WiFi-disable path; /var/run/netmanager_extender_flags by extender provisioning; /tmp/brokendevice by diagnostics; /tmp/crashed_play_state by AVT crash recovery; /tmp/memorylog = watchdog 4-file ring; conf/rdm{config,location} deleted by /devmode handler f_105e8d90.')
close(s['buttons_ir'],'Resolved: IR learn flow - learn FSM captures pulses, rejects over-ten-codes as non-repeat-style, succeeds via Successful long code learn; local store keys {vol_up_codes,vol_down_codes,vol_mute_codes} by remote id; on miss the code is POSTed to http://ir.ws.sonos.com/IRCode/ as <IRCode><value>..</value></IRCode> with a guid, then polled until Requested code not found resolves; failure surfaces UPNP_DP_LEARNONE_IR_CODE_NOT_FOUND.')
close(s['music_accounts'],'Resolved: account struct = {guest g, serialNum sn, hash h, serviceId, nickname, tombstone, auth{Token,OAuthDevID,OAuthToken,OAuthCode}, linkCode}; matching key is the {g,sn,h} triple; merge is version-gated replication rejecting {version,schema} mismatches; tombstones migrate; corruption detectors {emptyUUID,dupUUID,serial} route to corrupted/duplicate removal; preferred = serialNum from accountId.')
close(s['playlist_parsers'],'Resolved: per-format grammars documented in summary - ASX <ref href=/entryref, M3U/WLP/PLS sniffer chain, linkUrl extraction, HLS Playlist XML {HLSVersion,IsStatic,IsEncrypted,TargetDurationSec,CurrentBitRate,TrackEncryptionMethod/Format}; rendition selector is the ABR ladder {downgrade bitrate,already at minimum,stop at max} with the storeStream rejection taxonomy as the constraint set.')
close(D['shared_primitives']['binary_section_map']['text_region_map'],'Resolved: every block now carries an attribution verified by named-dynsym residency, vtable-method residency, or dense module-file literal clusters; no sampling-only attribution remains.')
close(s['wac_mode'],'Resolved: full dispatcher id census from f_10691034 - sequential r9-compare gates at ids {60:MuseHHID set, 53:recovery-AP connect, 9:network bounce, 3:netstart hello, 8:wifi-state event, 35:wifi conn/disc, 12:setup start/stop, 88:In-setup-mode query, 108:WAC timeout} plus previously decoded {36,37,39,41,42,46,47}. UX flow: button-triggered WAC enter writes /var/run/wac_mode -> netstartd drives SSID set + recovery AP -> device joins In-setup-mode until WAC timeout or completion.')
save()
print('all reapplied, intact')
