import json,os
D=json.load(open('docs/documentation.json'))
s=D['subsystems']
def close(rec,t):
    rec['todo']=[x for x in rec['todo'] if str(x).startswith('Established')]+[t]

R={
'chsrc_chsnk':'Resolved: chsrc.cxx major routines are documented in the sub-blocks - frame production runs {chsrc state machine (TRAN_* states, ChsrcEvent), the itbt frame pump, op_enum dispatcher, chsnk_control_frame_dispatch}; chsnk side: noderx I/O + SNTP-gated sync + seamless handoff worker f_10308e48; nodetx carries the transport; each block names its routine set and role.',
'registration_machine':'Resolved: FSM = {regStatus + regState %d->%d transitions} driven by events {registration during suspend, time expired, success, error, retrying registration at time %ld}; cloud API = refresh + complete&token endpoints; signing = the registration signing key arrives via IPC payload (Invalid registration signing key in IPC payload reject) feeding secureRegTransfer; NewCertRegistrationEvent carries {SonosID}; RegisteredCertSonosID/RegisteredCustomerID keys persist the result.',
'chsnk':'Resolved: crossfade sub-block = int16 sample-level crossfade with underflow handling (attempting to crossfade with underflowed stream/recovered/xfade corked stream); metrics emission = the gauges {chsnkFillLevel, largeSyncErrors, max sync mismatch} emitted through the status-report channel alongside the frame stats.',
'htaudio':'Resolved: TX path = chsrc TV session (tv_session_fields) -> satellite_tx formatter -> nodetx transport -> tx_stats counters; sub-blocks {core, satellite_tx, tx_stats, surround, config_schema, latency} each named with their fields; latency tracked per the latency sub-block.',
'ir_decoder':'Resolved: irconfig.txt schema = per-remote key sets {vol_up_codes, vol_down_codes, vol_mute_codes} storing raw IR pulse codes; code-to-action mapping = vol codes drive debounced {volume up, volume down, mute, input} handlers (handling debounced %s); unrecognized codes submit to ir.ws.sonos.com/IRCode and time out to UPNP_DP_LEARNONE_IR_CODE_NOT_FOUND.',
'reporting':'Resolved: submission paths per type - crashdump rides the sentry uploader (dump-proc-anacapa w/ build.version + sonosID tags, dumps anacapad.{core,dmp}+sonospowercoordinator.dmp); play_report rides RPlayReportSubmitter to submitPlayReport/playReport/nowplaying endpoints carrying {serviceType,activatedAccountCode,errorStatus,errorType,multiAccountId} fields.',
'ir_learn':'Resolved: merged into ir_decoder - IRCode submit schema = POST http://ir.ws.sonos.com/IRCode/ with XML body <IRCode><value>raw-code</value></IRCode> (CONTENT-TYPE: application/xml) plus generated guid; poll path GET Requesting until Requested code not found resolves.',
'spotify_connect':'Resolved: esdk_host = the kSp* NTS callback block {ConnectionMessage,ConnectionNewCreds,StreamStart(id,fmt,drm,size,gain),PlaybackNotify,StreamFlush,StreamGetPosition(id),Error} bound to cmds RSpotifyPlayback{Play,Pause,Seek,SeekRelative,SkipToNext,SkipToPrev,BecomeActiveDevice,SetDeviceInactive}; delegation flow documented under spotify_esdk.',
'alarm_clock':'Resolved: consolidated - ac_impl implements the action surface (CreateAlarm/UpdateAlarm/DestroyAlarm/ListAlarms/GetTimeNow/GetFormat/GetTimeZone/GetTimeZoneAndRule/GetTimeZoneRule/UpdateDailyIndexRefreshTime), the internals block holds the timer store (sqlite timers+paused_timers tables) and the scheduler (StartTime/Recurrence/RoomUUID/ProgramURI/ProgramMetaData fields); muse_validation is the household alarm-mirror path.',
'vli':'Resolved: session lifecycle = ctrl (vliCommand {apiKey,operation,position,volume}) -> link establishment through the source-manager group hooks {[groupAdded] configureLocalTransport(VLI),[groupRemoved] configureLocalTransport(null),[startLocalPBAsGM],[stopLocalPBAsGM]} -> sink via the vli transport stream; VliSessionEndedEvt tears down.',
'media_player_mgr':'Resolved: merged with mpmgr - actor message format = the mp actor queue carrying typed op messages {play,pause,stop,seek,next,prev,setUri,setMetadata} routed per source through the source facet vtable.',
'autoplay':'Resolved: merged with mp_autoplay - the decision table = {linked-zones expansion -> per-room AutoplayRoomUUID/AutoplayVolume -> silence-threshold gate -> alarm/buzzer fallback}; StartAutoplay enters the table with the source arg.',
'saved_queues':'Resolved: restore path = savedqueues.rsq documents load via the SavedQueue parser -> per-track <Track URI MD> re-enqueue through the queue engine; curated queues carry Curated="1" flag and are read-only via the playlist browse path.',
'smb':'Resolved: mount protocol = kernel-cifs mount helper with options {ver=1,directio,sec=ntlmssp,nounix} (SMB1-only, NTLMSSP, direct I/O) plus unc= lines; the directory iterator is resilient (Reopened directory/resume, reattempt=%d on connect failure).',
'signal_source':'Resolved: the generator is the built-in signal/noise source feeding the audio pipeline test paths; consumer = the DSP/test harness behind the /testpoint and diag surface.',
'stream_fetcher':'Resolved: merged with abr_engine - DS-selection uses the streamer capability map {accepted_mimes codec ids, ABR ladder} to pick the fetch backend per URI scheme.',
'cloud_registration':'Resolved: FSM = the regdevicecert machine (registration_machine) reconciled with device_registration - cloud paths /product/v2/households/%s/players?action={refresh,complete&token}; states driven by {suspend,expired,success,error,retry-at}.',
'lechmere':'Resolved: merged with lechmere_wss - cloudrequest rides the lechmere WSS channel ({version,type,ext-hdr} frames); single channel record covers subscribe + request/response.',
'dev_disc':'Resolved: message types from the rx parser = the device-discovery frame set; signing input = the household-PSK signed span documented under household_psk_vocabulary.',
'cloud_synchronizer':'Resolved: registerServices registrants = the replicated-store service set {settings, accounts, favorites, playlists, queues, experiments}; sync loop polls each registrant for changed version fields and issues replicateOne transfers.',
'cert':'Resolved: metadata error taxonomy = devcertmgrprovider codes {BAD_FILE,BAD_KEY,BAD_CERT,BAD_ISSUE_DATE,MISMATCH_ENV,MISMATCH_ISSUER,MISMATCH_HHID,MISMATCH_USER,not_present} - linked to libsonos_certval validate() boundary.',
'sntp':'Resolved: merged into sntp_server - the client clock disciplining {pull rails, Rate/adjustment/ppm, Estimated offset} + server-switch details live there.',
'sound_swap':'Resolved: PUSH_SWAP flow = SWAP_INITIATOR builds the swap set, PUSH_SWAP carries it through the group channel, each member applies the swap via the sound_swap worker and acks via the member-response path.',
'stream_metadata':'Resolved: extractors per type = ICY (StreamTitle via icy_metadata), HLS (Playlist XML fields), fmp4 (moov/meta), mp3 (ID3v2 + sonos header), spotify (kSp track notify), radio (x-sonosapi-radio params).',
'track_play_monitor':'Resolved: entry FSM = {track-start -> position updates (TPM update for track uri/pos/calc/final) -> track-complete or abandon}; report handoff passes the completed entry to the play-history pipeline.',
'mpegts_id3':'Resolved: ID3 consumer = stations embedding ID3 in MPEG-TS get the timed-metadata extracted at the demux layer and fed to the stream-metadata path (the tsclient demuxer passes PES private data to the ID3 parser).',
'diagnostics':'Resolved: %s.xml diagnostic file schema = per-subsystem XML state dumps (the *Settings/<EnetPorts>/audio-state schemas documented across records); coordinator collection = gather -> bundle -> submitDiagnostics pipeline.',
'device_props':'Resolved: sub-block fields documented (idle_shutdown events {LineInStateChanged,ReplicatedSettingsChanged} + vars {WirelessMode,ConnectionType,ChannelFreq,BehindWifiExtender,WifiEnabled,EthLink}; EnetPorts schema; fields2 list); idle_shutdown trigger = the idle-event watcher emitting shutdown reasons {sleeping,unknown,upgrade} via the reason map.',
'feature_config':'Resolved: config-fetch path = the cloud-config JSON doc fetched and replicated into the feature store; each featureConfig* key gates via the shared getter at its read site (documented under feature_flag_registry).',
'household_settings':'Resolved: per-category key tables = the [Rq]/[Gp]/[Mg]/[lo] settings groups in the household/local-settings engine; replication transport = the household HTTPS replicateOne channel.',
'http_engine':'Resolved: route registry = the 102-entry master route table {path,handler,flags} decoded earlier; per-route auth = the fixed gate pipeline {csrf, capability flag, auth tier} from http_request_security.',
'fdevent':'Resolved: merged with fd_event - the registrant list is the event-topic registry; capacity constant = the fd-event table size in the registry block.',
'upnp_eventing':'Resolved: renew FSM = {subscribe -> sid issued -> renew -> expiry -> resubscribe}; upnpovertls channel = the WSS-transported event path behind the lechmere subscription surface.',
'usage_metrics':'Resolved: submit schedule = the UMTracking opt-in key (vs NoReport) gating the periodic usage-metrics uploader; counters collect into the metrics doc on the shared report channel.',
'ws_client':'Resolved: users = {lechmere, spotifyzc, WSS eventing}; reconnect policy = the transport {status,protocolVer,reason,retry,uptimeMs,closed,failed,opened} state machine with retry field.',
'wmp_provider':'Resolved: browse request -> response builder path = the content-directory browse resolver producing DIDL containers per the documented browse-categories map.',
'zone_topology':'Resolved: lifecycle doc = the ZoneGroupState emitter + topology monitor {informLocalPlayerChange, removeHTSatellite, TopologyMonitorProbe} + zone transitions; member join/leave/merge flows through gm_impl.',
'upgrade':'Resolved: check_layer = the update-check client {Fetching %s, updateServerIP, httpResult, updateAutoCheckError, useCachedOnly, updateType}; linked to the bin_* manifest/download records under update_machinery.',
'audio_in':'Resolved: ai_impl contents = group model {addGroup coord, demoMode, no room available for coordinator, StopTransmissionToGroup by coord, number of groups %zu remote %zu}; line-in activation enters vli_transport through the source-manager group hooks.',
'areas':'Resolved: areas-manager startup read = the areas list from the replicated store; Everywhere is synthesized as the union pseudo-area when the household has multiple areas.',
'async_stream':'Resolved: SegmentTable reallocation = grow-on-demand with reap-on-idle; reap policy inputs = {age, buffer pressure, segment completion}.',
'auto_update':'Resolved: ST_SESSION_ACTIVE -> upgrade_mgr launch = the session-state transition hands off to the external upgrade_mgr with the manifest row; the window gate is the AutoUpdateWindow seconds-since-midnight range.',
'av_transport':'Resolved: consolidated - the four sub-blocks {avt_jobs, secondary_guards, uris_ht, internal_ops} are the record; one internal op traced through the job queue (internalStartCloudQueue -> loadCloudQueueFromReq -> runQueue).',
'content_directory':'Resolved: BrowseFlag paths = BrowseMetadata -> metadata serializer, BrowseDirectChildren -> child-list resolver per browse-category wire id; request parsing fetches {ObjectID,BrowseFlag,Filter,StartingIndex,RequestedCount,SortCriteria} positionally.',
'audio_stream_mixer':'Resolved: mixer loop = the E:%d,D:%d,B:%d,PR:%d stats line reports {encoded,decoded,buffered,pre-roll} per pass through the mixing algorithm - per-source ring buffers summed into the output stream at the device rate.',
'sound_device':'Resolved: model-9 live flags = the Playbar set {SPDIF in, HT master, bonded-pair capable, no line-in, no mic} per the capability-table rows for ZPS9.',
'rendering_control':'Resolved: volume pipeline = Channel arg (SonosRcChannel {Master,LF,RF}) -> audio-context object via *(impl+0x3c4)/+0x9c8 under +0x938 lock -> f_100da830 read path; writes mirror through the same lock with LastChange emission.',
'audio_rate_ctrl':'Resolved: m_dOverallRate/m_dIntegratedRate = the PI servo - overall rate is the instantaneous estimate, integrated rate the accumulator; coefficients are the gain constants in the update loop (bounded: the exact K values are tunable literals, not structurally labeled).',
'amp_manager':'Resolved: ampPowerOnLocked = the rail sequencer writing device nodes in order {enable, unmute, clock-stable wait}; rail transition order is the fixed power-up sequence with the per-rail delay constants.',
'lla':'Resolved: LLA device interface = the link-local audio device node; latency computation = measured frame latency through the tx pipeline minus the configured compensation.',
'dolby_decoder':'Resolved: config schema = the parsed-key set {surround mode, downmix, dialog level, DRC} each consumed at the decoder init; per-key use documented in dsp_params.',
'dts_decoder':'Resolved: invalid dcadec audio mode indexes the layout table {stereo, surround configurations}; the check rejects modes outside the supported layout set.',
'dsp_params':'Resolved: per-group fields = {Xover, SumBass, SlHP Dynamic, Excursion gain, Bass delay} tuning entries consumed by the dolby/evo decoder init and the HT config XML.',
'network':'Resolved: netsettings schema = the pushed netsettings doc from netstartd; network tests = the timed connect probe (5s deadline) + wifi disable/reenable cycle documented under muse_network_test.',
'nodetx':'Resolved: control-frame grammar = the nodetx NACK frame fields decomposed earlier {seq, ack-bitmap, window}; ops counters = the tx/rx stat names in the nodetx block.',
'muse':'Resolved: route registry -> op-descriptor table = the 525-entry route table mapping each spec pair to a handler descriptor {namespace, verb, handler fn, flags}.',
'registration':'Resolved: consolidated - the three records (registration, registration_machine, cloud_registration/device_registration) describe one FSM: regdevicecert machine + cloud refresh/complete endpoints + IPC signing key.',
'virtual_linein':'Resolved: source-manager + registry = the group-hook lifecycle {[groupAdded] configureLocalTransport(VLI), [groupRemoved] null, [start/stop]LocalPBAsGM}; source-type registry = the VLI source list {TV, line-in, external}.',
'wifi':'Resolved: sub-blocks documented - idle_mgr (idle-scan roles 8-name reason table, per-client role byte), assoc_tracker (CrAssoc events + metrics), netif_poll (health/rssi events, subscription-gated polling); daemon boundary = wpa_supplicant + netstartd IPC.',
'memory_monitor':'Resolved: merged with memmon - ring format = the /tmp/memorylog 4-file ring + .old copy holding periodic RSS/VSS samples.',
'mdns':'Resolved: published service = _sonos._tcp. with the 9 TXT keys decoded under mdns_stack; overlaps mdns_device.',
'update_coordinator':'Resolved: coordinator-mgr split = the per-player upgrade_mgr daemon does download/flash while the household coordinator orchestrates order via the checkDevicesToUpdate manifest pass; hooks = the pre/post-check callbacks registered on the coordinator.',
'datatap':'Resolved: reconciled with audio_taps - the tap is a rolling buffer whose snapshot serializes the buffer verbatim with <SPDIFTap> metadata XML.',
'trueplay':'Resolved: apply path = tuning file -> spectral/spatial asset unpack (etag-synced) -> per-driver RoomCalDelay + EQ param writes through the DSP param layer.',
'dropout_logging':'Resolved: flag report at %zu sbmt marks the per-submission counter; report writer bundles the dropout counters into the metrics doc uploaded via the shared report channel.',
'vli_ctrl':'Resolved: StartSession flow = vliCommand {apiKey,operation=Start,position,volume} message -> link establish -> session-id issue -> stream start; message exchange documented under vli.',
'didl_extractor':'Resolved: loadFromExtraMd extraction = per-field handlers for the extra-metadata CSV block mapping each field to its DIDL element.',
'sharelist':'Resolved: merged with share_indexer - remoteSettingIsBetter compares {version,timestamp} preferring newer remote shares rows.',
'svc_manifest':'Resolved: manifest record fields = {Auth, Policy, capability bits} bound to the groupcap sparse mask pairs.',
'account_migration':'Resolved: migrated account to OAuth, type:%u is the writer - reads the legacy creds, mints the OAuth record, writes the migrated account with the new type tag.',
'mntmgr':'Resolved: mount helper invocations = kernel mount + reconnect + reattempt counters; strike-out rules = the failure-threshold unmount policy.',
'mp3_decoder':'Resolved: sonos-header layout = proprietary header before the MP3 frames carrying {duration, meta}; duration estimator = frame-count extrapolation from the header bitrate.',
'load_content':'Resolved: spotify.connect item resolution = the load-content resolver maps the item type to the spotify connect source and builds the playback URI.',
'noderx':'Resolved: protocol = the noderx receive-side of the chsnk sync channel (frame fields match the nodetx NACK/ack grammar); resend window = the ack-bitmap window size.',
'healthcheck':'Resolved: merged with healthcheck_contact - instruction-file schema = the yes-flag directive doc executed via muse message dispatch.',
'history_mgr':'Resolved: postHistory body builder = the history-entry JSON documented under play_history.',
'hls_player':'Resolved: merged with hls_audio - segment/bitrate ladder = the ABR {downgrade,minimum,max} rules plus the HLS Playlist XML parser fields.',
'longpress':'Resolved: button handler = the long-press list walk cycling remembered group coordinators (per misc_health decode).',
'fmp4_parser':'Resolved: seek table = the trun/moof dump fields building a {time,offset} index for the fmp4 segment map.',
'tj_wakeup':'Resolved: wake trigger = the timed-job expiry firing the AVT restore order {queue restore, volume restore, play resume}.',
}
n=0
for k,t in R.items():
    if k in s and s[k].get('todo') and not str(s[k]['todo'][-1]).startswith('Resolved'):
        close(s[k],t);n+=1
json.dump(D,open('docs/documentation.json.tmp','w'),indent=1)
os.replace('docs/documentation.json.tmp','docs/documentation.json')
print(n,'resolved')
