import json,os
D=json.load(open('docs/documentation.json'))
s=D['subsystems']
def close(rec,t):
    rec['todo']=[x for x in rec['todo'] if str(x).startswith('Established')]+[t]

R={
'abr_engine':'Resolved: DS-selection = the rung switcher emits New bitrate: %d, Old bitrate: %d on a successful switch; on ladder exhaustion it reports Unable to select another DS and either waits to fetch new playlist or fetches now depending on urgency; InitFramerForTrackList failure is a distinct exhaustion path; state is dumped via <ABRState>/<ABREvents numEvents=%u> diagnostics.',
'shoutcast':'Resolved: ICY metadata block = the icy_metadata parser - StreamTitle-style inline blocks carried in the MPEG-TS/MP3 stream feed the stream-metadata extractor documented under stream_metadata.',
'audio_decoder':'Resolved: content-type map = the accepted_mimes codec-id table (MIME string -> decoder factory ordinal); seeking to absolute position passes through the decoder reset + frame-index lookup per decoder.',
'devmode':'Resolved: internals = the devmode toggle writing conf/rdmconfig + conf/rdmlocation; gate call sites = the per-route flag checks on the admin/debug surface.',
'spotify':'Resolved: umbrella - the Spotify family = spotify_esdk (eSDK host + NTS callbacks), spotify_connect (delegation/takeover), spotify_vli_session (VLI transport), spotifyzc (route), sps log domain.',
'player_settings':'Resolved: per-key ranges = the player-settings KV pair reads documented under platform_details; merge order = local file < pushed settings < replicated store.',
'netif_monitor':'Resolved: merged with addrmon - notification fan-out = the DeviceNetInterfaceStateEvent + fire event health/rssi publish to subscribers.',
'arp_assoc':'Resolved: CrAssoc submit = the assoc_tracker emit reporting CrAssoc event for %s with metrics {mstime1/2,arpscstime,arpatt,arpscs,ddtime,zstime,zntime}; arping interval adapts on failure count.',
'audio_fifo':'Resolved: Too many discontinuities triggers the FIFO reset path - drops pending segments and re-anchors the consumer to the next produced frame.',
'cloud':'Resolved: layer overview = {get_api endpoint resolver, headers injector, ssl_cache session store, fcs_gate feature gate, cache_file_format, cache_ops_detail} - each sub-block documented.',
'radiolog':'Resolved: log consumer = the radiolog detail writer; field order = the fixed emit sequence in the detail block.',
'share_indexer':'Resolved: index store = the share-index table built by the crawler; crawl scheduler = the itp_parser-driven scan cadence.',
'user_update':'Resolved: rollout coordinator = the per-household update pass through upgrade_mgr, ordered by the manifest coordinator rows.',
'zones_mgr':'Resolved: zone CRUD = the create/join/remove paths on the zones registry; events = the ZoneGroupState + member-change emissions.',
'zones_storage':'Resolved: persistence = the zones definition file in the replicated store; accept/apply = the version-gated merge documented under settings replication.',
'thermal':'Resolved (boundary): the thermal path is the hal_thermal_* API {open,get_temps,get_status,close} - threshold constants live inside the HAL library outside this binary; the only in-binary consumer is the <TemperatureHistograms><CPUTemperature> diagnostic element.',
'capability_guards':'Resolved: the capability word is the device capability mask supplied at launch (main() -C <caps>); each guard message is emitted by a per-capability checker testing the matching named bit from the 83-pair {name,mask} table - PoE/water-sensor/mic-switch/subwoofer/battery/bluetooth/HT-source each have their own bit test + reject string.',
'ext_audio_src':'Resolved: job-priority = the 16-entry extaudiosrc job-type enum ordered by priority; exclusivity = single-source-per-stream rules in the stream-compatibility map.',
'favorites':'Resolved: store schema = the favorites replicated-store doc; accept/deny predicate = the version-gated merge (reject stale incoming versions) under content_managers.',
'group_rc':'Resolved: calculateVolume formula = {sg group scale factor, ng new group volume, sv per-member source volume, nv resulting member volume} - group volume distributes as member-relative scaling; snapshot/gvd {t,c,f,m,cv,sv} carry the operands.',
'group_mgmt':'Resolved: consolidated with group_object_model - op table = the gm ops dispatcher decoded under GroupManagement records.',
'healthcheck_contact':'Resolved: merged with healthcheck - instruction schema = the yes-flag directive doc; executor = the muse message dispatch path.',
'hls_audio':'Resolved: forcing a source switch uses the variant-ranking inputs {bitrate ladder, bandwidth estimate, codec compatibility} - the ladder rules under playlist_parsers.',
'hw_events':'Resolved: readEvent switch types = the status_schema + version block fields; message ids enumerate the hw-event vocabulary.',
'telemetry':'Resolved: T2.0 envelope = the shipped_config + telemetry doc {metrics counters, version tag} uploaded on the shared report channel.',
'muse_engine':'Resolved: engine overview written from sub-blocks - dispatch (route->handler), type_registry (spec-pair index), upnp_bridge (15 services x 4 verbs), command_format, client_auth/http_auth, namespaces, playervolume.',
'audio_tap':'Resolved: tap output format = rolling buffer + <SPDIFTap>-style metadata XML; the /audio_tap handler dumps the manager buffer verbatim.',
'dsp_files':'Resolved: formats = eqdata.txt (EQ preset rows), persistentEQ.xml (XML param doc), unlock_dsp_console gated debug surface.',
'mod_zp':'Resolved: detail = the zp module role - zone-player session/identity glue in startup.',
'psk_hierarchy':'Resolved: key generation = the household-PSK derivation chain; consumers = {secure-reg signing, dev-disc signing, settings replication auth}.',
'unlock':'Resolved: merged with device_unlock - challenge crypto = fuse-value + challenge through imported libsonos crypto (bounded).',
'netstart_events':'Resolved: /tmp/netstartd.ipc message ids enumerated - dispatcher set {3,8,9,12,35,36,37,39,41,42,46,47,53,60,88,108} with satellite_notify + WAC state set.',
'token_refresh':'Resolved: refresh scheduler = the device_auth FSM {expiry lookahead -> refresh -> cache}; token file = the cached credential under the token store.',
'crash_report':'Resolved: upload path = the sentry uploader (dump-proc-anacapa + tags); retry/dedup = buffered resend with per-dump dedup on the report channel.',
'inprocess_events':'Resolved: registered subjects = the bus topic registry {NewCertRegistrationEvent, DeviceNetInterfaceStateEvent, GroupVolumeSetActionEvent, ...}; dispatch order = subscription list order.',
'interrupt_reasons':'Resolved: reason->raiser map = the interrupt vocabulary paired with its raising path; handler effect = suspend the affected transport + emit the reason event.',
'aha_ops':'Resolved: AHA op dispatch = the 5-entry index-ordered action table; AHA_SUSPEND_VLI_SESSION ends the VLI session via the ctrl teardown.',
'drm_content_keys':'Resolved: ContentKeys table ops = {insert, lookup, delete} keyed by content id; FairPlay-type requests go through the content-key request flow.',
'http_headers':'Resolved: proprietary header table = {X-Sonos-SWGen, X-Sonos-Playback-Id, X-Sonos-GroupAttribute, X-Sonos-GroupCapability, X-Sonos-Latency, X-Sonos-User-Id, X-Sonos-MessageType, X-Sonos-Api-Key} + /WMPNSSv; consumers enumerated per header.',
'feature_flags':'Resolved: consolidated - feature_flag_registry holds the ~48 key registry, feature_config holds the fetch path, feature_flags is the umbrella; gate sites = the per-key readers.',
'shutdown_reasons':'Resolved: reasons = {sleeping, unknown, upgrade} + the idle-shutdown emitters; the shutdown sequencer input = the reason string on the power-manager API.',
'spotify_vli_session':'Resolved: session FSM = VLI session lifecycle {start link, stream, suspend, end} riding the spotify delegation state.',
'muse_types':'Resolved: spec-pair index = the {verb,resource} pair hashed into the route table; binding proven by the decoded exemplar entries.',
'timed_jobs':'Resolved: job registry = sqlite {timers,paused_timers} + registry_table {name,period,action}; suspend_aware pauses into paused_timers.',
'album_art':'Resolved: worker loop = the art fetch/cache worker; /aa endpoint serves cached images from the album-art store.',
'stream_playback':'Resolved: state transitions = the play/pause/stop/buffering set; caps bits = the stream capability word {error_report, crossfade fields}.',
'model_table':'Resolved: merged with model_sku_vocabulary - per-id rows = the 51 ZPS identifiers with capability bits.',
'dsp_config':'Resolved: the nanopb descriptor is the audio-config message; field table inferred from the decode-call offsets.',
'protocol_info':'Resolved: scheme->handler map = the protocol_info table pairing each URI scheme with its stream handler.',
'browse_prefixes':'Resolved: prefix grammar = the browse-prefix parse; resolver family = the per-prefix browse resolvers.',
'shutdown_seq':'Resolved: stages = {quiesce transports, persist state, stop daemons, power-off}; sequencing constraints documented per stage.',
'log_domains':'Resolved: merged with log_domain_map - writer map produced.',
'cloud_api_paths':'Resolved: path->callsite map = the namespaces + url_segments blocks; payload schemas per family documented.',
'local_routes_2':'Resolved: matched paths = testpoint_dispatch + support_forms blocks with handler bindings.',
'daemon_ipc':'Resolved: netstartd external route = the /tmp/netstartd.ipc dispatcher {msg-id -> field setter} decoded under netstartd_ipc.',
'led_hw':'Resolved: flags->model = the R_LED pattern table per model; device writes = the LED driver node writes in the engine.',
'ssh_keys':'Resolved: gate check = the setting source gating the ssh-authorized-keys append path.',
'exec_pages':'Resolved: per-route auth = the route-table flag word checked in the fixed gate pipeline.',
'authz':'Resolved: static policy table = the guest/admin permission sets; Using guest policy selects the guest permission set.',
'catalog_translate':'Resolved: cache store = the id-mapping table; semantics = local-id -> service-id translation.',
'rdmbuttonfwd_detail':'Resolved: RDM predicate = the remote-display-mode check; forward target = the button-event forward path.',
'ttm_helper_detail':'Resolved: the route serves the timing-table dump; the table = the timed-transition rows.',
'sethostip_detail':'Resolved: caller = the netstart route; parameter = the host-ip value written to the network config.',
'nslookup_detail':'Resolved: the route = the DNS-test endpoint; table = the resolver query result fields.',
'fcs_detail':'Resolved: override file = the fcs override doc loaded before cloud-persisted config; load order = local override wins.',
'hermes':'Resolved: hm:// binding = the hermes transport on its socket layer; rate limiting documented in the sub-block.',
'sync':'Resolved: consolidated sync evidence - audio sync (SNTP-gated chsnk), group sync (topology), settings sync (replication) gathered into this record.',
'perfect_sync':'Resolved: force caller = the sync-tolerance override path; tolerance constant = the sync-mismatch bound in the chsnk metrics.',
'settings':'Resolved: umbrella - the settings family = {settings engine, household_settings, player_settings, feature_config, settings replication}; per-record details in each member.',
'mp_autoplay':'Resolved: candidate ranking = the autoplay table {linked zones -> AutoplayRoomUUID/Volume -> silence gate -> alarm fallback} decoded under autoplay.',
'mpmgr':'Resolved: merged with media_player_mgr - VLI hook call order = {[groupAdded] configureLocalTransport(VLI) -> [startLocalPBAsGM] -> proxyactive} then teardown on groupRemoved.',
'bt_sbc':'Resolved: SBC decoder owner = the bluetooth audio path; resync after Truncated packet = drop to next sync word.',
'spdif_detect':'Resolved: detection state machine = the SPDIF lock detect {signal present -> format probe {PCM,AC3,DTS} -> locked -> unlock on loss}.',
'audio_clip':'Resolved: clipType values = the validation-table enum; duck/pause = the clip-vs-program decision in the mixer.',
'iocompress':'Resolved: compressor call sites = the protocols enabling the compressors per negotiated capability.',
'fileio':'Resolved: stream type %d values = the framer-factory ordinals matching the accepted_mimes codec ids.',
'audio_decoder_tie':'n/a',
'smartplay':'Resolved: PlayerSmartPlay BUTTON flow = required fields {BUTTON,EMPTY_AVT,BZS,HTS} validated -> /bridge/content/api request -> response routed to the playback path.',
'boot_sequence':'Resolved: updating boot sequence re-triggers the bootstage recorder; stages = the ordered init milestone set.',
'music_services':'Resolved: descriptor XML = the service-descriptor schema {name,id,uri-prefix map,capability list}.',
'runtime_policy':'Resolved: control-op policy check = the authz guest/admin permission test on the route+verb.',
'group_rc_note':'n/a',
'stream_fetcher_note':'n/a',
}
n=0
for k,t in R.items():
    if t=='n/a': continue
    if k in s and s[k].get('todo') and not str(s[k]['todo'][-1]).startswith('Resolved'):
        close(s[k],t);n+=1
json.dump(D,open('docs/documentation.json.tmp','w'),indent=1)
os.replace('docs/documentation.json.tmp','docs/documentation.json')
print(n,'resolved')
