import json,os
D=json.load(open('docs/documentation.json'))
s=D['subsystems']
def close(rec,t):
    rec['todo']=[x for x in rec['todo'] if str(x).startswith('Established')]+[t]

R={
'effective_settings':'Resolved: [Mg] key-id store = the group registry behind v1/players/{playerId}/effectiveSettings{,/{groupName}} + household variants; verbs {getAllSettings,getSettingsGroup,updateAllSettings,updateSettingsGroup} map each registry group to a route.',
'ibt':'Resolved: consolidated - plan lifecycle {already generated ibt plan/no action, executing ibt plan for command %s, failed to generate target list/plan}; intendedTargets grammar {implicit/explicit target parsed, invalid intendedTargets, command does not support intendedTargets} + target_param_check sub-block.',
'spotifyzc':'Resolved: merged with spotify_zeroconf - handler sub-block covers the zc request path {path,method,userAgent,esdkVersion,action} + GC gate.',
'sonarctl_detail':'Resolved: route binding = the gate f_105489fc -> method check (r9==1 POST) -> f_100b4614/f_100b4364/f_100b4388 response helpers; command set = sonar-tone flush ops {flushing sonar tones, Flushed} for sonar-cal.',
'trueplay_api':'Resolved: node API per method = the factory TrueplayAPIFactory + initNode/initNodeMajorVersion version negotiation {Build version for TP API, Updating Trueplay SDK version, not supported -> previous version, already in use}; node_fsm + codec sub-blocks hold the per-method flow.',
'device_registration':'Resolved: regState values = the FSM transitions logged as regState changed %d -> %d through {during suspend, time expired, success, error, retry-at}; signing-key IPC payload = the Invalid registration signing key reject on the IPC set/clear path (registration_machine).',
'hhsettings_rest':'Resolved: category permission table = path grammar {public/{key}, restricted/{key}, restricted-admin/{key}} with visibility sub-block; key registry = the HHSettingsMgr validated key set behind the error vocabulary.',
'memmon':'Resolved: merged with memory_monitor - ring = /tmp/memorylog/log.%d (+.old rotation), fed by /proc/meminfo {MemAvailable,MemFree} + /proc/%s/{statm,cmdline} reads.',
'mdns_controller':'Resolved: registration calls = the service lifecycle {register-once guard, TXTRecord populate, value update/remove with dup guards, unregister}; service records = the _sonos._tcp TXT set under mdns_device/mdns_stack.',
'overrideconfig':'Resolved: the committed override file is consumed by the fcs/cloud-config reader (fcs_detail) - local override wins over cloud-persisted config.',
'json_parser':'Resolved: implementation = the embedded JSON parser identified by its error enum {Exceeded max depth, Invalid unicode escape, Invalid escape, Invalid string character, Invalid numeric character, Unexpected token, Sequence too long, Missing required value, Invalid value, Out Of Memory, Unexpected error}; callers = every muse/cloud JSON consumer.',
'event_loop':'Resolved: registrants = the eventLoopThreadPool consumers {scopeDefault, scope:mtx, scope:cv, scopeHttpClient}; scheduling = watchdogTimestamp + elapsed-time logging + has-no-more-work shutdown path.',
'devicecertmanager':'Resolved: differentiated from the other cert managers - this one owns ETag-cached cert downloads {requestTimeMS, downloadStatusCode, httpResultCode, previousETag -> downloaded|unchanged} with refresh-job scheduling on unknown metadata state; certval validation + registration signing live in the sibling records.',
'zpinfo_dpimpl':'Resolved: var->producer map = {WirelessMode,ConnectionType,ChannelFreq,BehindWifiExtender,WifiEnabled,EthLink} from the netif layer, {SettingsReplicationState,SecureRegState,IsIdle,MoreInfo} from the settings/registration monitors; events {LineInStateChanged,ReplicatedSettingsChanged} drive the idle FSM.',
'enet_stats':'Resolved: report emitter = the <EnetPorts> XML writer with EthPrtStats {rxPackets,txPackets,rxBytes,txBytes,rxErrors,rxDropped,txDropped,multicasts,collisions} + EthIntrf detail; the /status page section renders this block.',
'fd_event':'Resolved: capacity constant = the exceeded the fd capacity of %d literal; registrants = the {fdevent.signal/write, wait.poll, check.poll, reset.read, removeFd, waitForEvent} ops + EventSync + epoll trio.',
'error_codes':'Resolved: error-code families enumerated - SOAP fault domains {4xx/5xx vendor ladders}, the 107-entry internal result-namespace table (index==code), the store-commit {501,800,801,802} ladder, muse result codes, jwt/authz enums; rze sub-block holds the RZE family.',
'spotify_zeroconf':'Resolved: zeroconf login = getInfo/addUser over the zc routes with GC gate (Non-GC returning 404, reject zc req), ver 2.9.0 client types {Partner,Spotify}, results {SpotZc_Failure,SpotZc_Success}; URIs x-spotify:// + x-spotify-file://.',
'spotify_smapi_ctrl':'Resolved: transition states = TransitionAck {pos, preLogout pos, transAck} + Begin AwaitingTransitionAck [preLogout] + discarding pre-transition position; setPositionInfo carries {trackId, position, duration, bLastReport}.',
'spotify_thread':'Resolved: request serialization = single-request constraint (Already have a spotify request in progress) + per-request Executing %s/%s timeout; rate limit constants = the telemetry rate-limit guards.',
'smapi_descriptor':'Resolved: descriptor schema = {apiKey, advertising, presentationMap, strings, reporting, browse, Moment} + accountTiers {paidLimited, paidPremium} + capability checkboxes {noMultiAccount, contextHeaders, deviceCapabilities}.',
'cpu_monitor':'Resolved: sampler = the /proc/stat reader printing the [%d] usr sys idle sIRQ table; consumer = the cpu report + cpu%d switched to a shutdown state watcher.',
'ht_audio_sources':'Resolved: -as suffix map = {tv-sat-as satellite RX, tv-gm-dm-as GM downmix, tv-proc-as TV processor, AIHomeTheater AI path, chsnk-sat-as chsnk satellite} bound to DSP-graph taps; ForceSubmitTvSessionReport op documented.',
'ht_telemetry':'Resolved: report assembly = the schema {corrId, cid set/clr, sessionLength, sessionPlayTime, connectionType, GCUUID, GCBootSeq, GCTimeStart/End, inputRate, dataBurstType, contentType, playSeconds, forced, topoType} tagged {tv_usage, zpHTInputSession} -> shared report channel.',
'sentry_upload':'Resolved: upload payload = per-route dumps {anacapad.core, anacapad.dmp, sonospowercoordinator.dmp} over routes {/upload,/watchdog,/anacapad-external,/sonospowercoordinator-external,/watchdog-legacy,/legacy-to-sentry,/btmanager-external,/sonosledmgrd-external,/netstartd-external}; destination = the sentry ingest host.',
'tv_processor':'Resolved: decoder selections + FSM = the state enum {READING,PARSING,DECODING,DECODER_DSP,NOISE_SILENCE_DETECTION,WRITING,WAITING,INPUT_ERROR,RECORDING,MONITOR_IDLING,MONITORING} + tv_block_descriptor + chaos_params; <TVProc> dump carries the full state.',
'htaudio_chproc':'Resolved: tv channel map changed -> routing rebuild = the chproc remap re-derives {htain,htaoutl,htaoutr,htaouts,remote,downmix} streams + DRC states {bNightMode, dialogEnhancementLevel, speechExtraction}.',
'smapi_client':'Resolved: getMediaURI envelope = the Services/1.1 namespace action {getMediaURI} built like getSessionId/getStreamingMetadata siblings, protocol_info sub-block holds the wire form.',
'account_actions':'Resolved: action->dispatch map = the arg set {VariableName,StringValue,AccountUDN,AccountNickname,AccountType,WebCode,AccountPassword,NewAccountPassword,NewAccountMd,AccountToken,AccountKey,OAuthDeviceID,AuthorizationCode,RedirectURI,UserIdHashCode,AccountTier,AccountUI} -> account-store write path.',
'zgt_errors':'Resolved: ZGT fault paths = {ReportUnresponsiveDevice handling, GetZoneGroupAttributes rejects {No valid UUID in request server, TServer is not valid for request, TRequest is invalid in the control server}}.',
'desired_settings':'Resolved: desired->applied transition = the {DesiredTimeFormat,DesiredDateFormat,DesiredTimeServer,DesiredTime,TimeZoneForDesiredTime,HouseholdUTCTime,DesiredDailyIndexRefreshTime} keys applied through the settings manager on receipt.',
'zgt_schema':'Resolved: per-attribute domains = <ZoneGroupState><ZoneGroups><ZoneGroup Coordinator ID> + <VanishedDevices>/<QuarantinedDevices> <Device {UUID,Reason,ModelInfo,Mac,LastKnownIP,LastSeenUTC}> + ZonePlayer attr set; vanish_and_remove covers lifecycle.',
'topology_base':'Resolved: ZP record = the ops set {RTopologyImpl,new_or_updated_zp,upgrade_report,informReplicatedSettingsChange,informLocalSecureRegStateChange,informLocalIdleStateChange,updateLocalMoreInfo,getZPUUIDs,isLocalZPIdle} + emitted events.',
'wireless_modes':'Resolved: mode FSM = {SONOSNET,INVALID,ETHERNET,STATION_SATELLITE,SONOSNET_SATELLITE_STATION_PRIMARY,STATION}; transitions driven by netconfig + <Wireless><WirelessInfo> dump.',
'audio_decoders':'Resolved: decoder-selection = the codec factory keyed by accepted_mimes id; AAC param parsing = the adts_aiff_framer path; vorbis error set + detail sub-block documented.',
'product_models':'Resolved: codename->model-id = the {Default,Playbar,ElRey,Bravo,Hideout,Pallas,Apollo,Lasso,Play1,TitanWOW-{T,P,G},Monaco,Play3,Encore,Alpine,Pinewood,Prima,Mojave,Optimo2,Optimo1} set paired with ZPS ids; merged with model_table.',
'htaudio_satellite_tx':'Resolved: packet format = the stats schema {timeToPlay, txSent, txErrors, serializationErrors, numLateFrames} + control_frames sub-block describing the TX frame.',
'spdif_burst':'Resolved: burst-encoder selection = the supported enum {Dolby Digital,DD Surround,DD Plus,Atmos DD+,TrueHD,Atmos TrueHD,MAT,Atmos MAT,DTS Type1-3} vs unsupported {NULL Burst,Pause Burst,AC-3} + code_module/pic_call_model.',
'addrmon':'Resolved: notification fan-out = RTM_NEWLINK/RTM_GETLINK netlink events -> selthrd.RIfAddressMonitor.{reset,data,except,timeout} -> netconfig_fsm consumers.',
'audiotap_manager':'Resolved: max-taps guard comparand = the available-capacity constant; debug parameter protocol = {Active Tap %s, Closing Tap %s} ops under raudiotapMutex with async-request + poll errors.',
'cloud_services':'Resolved: service->wrapper map = host patterns {sslauth.sonos.com, lower-sslauth host, generic %s.%s%s, lechmere.%s.ws.sonos.com, /firmware/swgen/%u/latest/} with service names {clientdata,crash-upload,feature-config,music-history,lechmere-v1,...}; env-resolution via the env prefix.',
'ssl_sessions':'Resolved: cache record = Cached SSL session for %s:%d entries + client-cache file guards + new-session-ticket handling during mbedtls ops.',
'http_client':'Resolved: thread-pool = performAsync scheduling over the pool {not scheduled. No active thread pool available, Client not setup, empty URL, Curl error, Request timed out in %lld ms, curl_multi_perform}.',
'browse_ids':'Resolved: live vs dead = the browse-id table {ALBARTIST,LIBARTIST,LIBALBUM,LIBGENRE,LIBTRACKS,LIBPLAYLISTS,LIBSTATIONS,LIBMUSIC} + genre set vs the Browse dispatch - ids reachable through the resolver are live.',
'dataio':'Resolved: awaitAvail accounting = the dataio.poll waits; SSL session-cache interaction = the parsed {ETag,cache-control,Last-Modified} fields + session reuse.',
'chanmapset':'Resolved: upd/chk exchange = the sync protocol {upd [%zu] error stored uuid, chk [%zu] remote uuid/state} + validator {Initializer List too large truncating, Duplicate entry}.',
'httpcache':'Resolved: Invalidating remote caches = hash-based invalidation propagated to remote players {cacheHashes, hashLocal/hashRemote compare, Cache not found/Invalidated local}.',
'mdns_device':'Resolved: TXT semantics = {byebyereason, protovers, minApiVersion, mhhid, hhsslport, variant, mdnssequence, locationid}; update triggers = topology/household changes.',
'mdns_discovery':'Resolved: Notify topology consumer = the topology datastore; schema = the TXT-validated peer record with household filter + bye-bye reason tracking.',
'queue_schema':'Resolved: string-table dedup = <Queue> dump fields {EntriesMax/Used/HighWater, StringTableSize/Used/HighWater}; capacity = EntriesMax constant.',
'accounts_replication':'Resolved: pull/push version compare = the ops {markAccountsForPushLocked, addAccount* family, modifyAccount} using replicated-store version fields; detail sub-block holds the flow.',
'audioin_groups':'Resolved: addGroup/removeGroup -> transmission = the coordinator-keyed group map {Adding group with coord/demoMode, no room available, added number of groups remote} -> StopTransmissionToGroup teardown.',
'avt_impl':'Resolved: TX selector = {Using HTAudio TV TX for GM %s, Using CHSRC TX for GM %s} chosen per session type + Why are we telling HTAP to play %s + setting tvInputFormat + iSCS clock install/remove; persistence + actor documented.',
'vli_transport':'Resolved: setup sequence = setTransportToVLIStreamURI {URI,autoplay,become gc} -> activating source with URI/VliGroupID -> StartTransmission (VLI) -> events; incompatible-VLI-type + going-to-stopped paths covered.',
'avt_lastchange':'Resolved: emit path = transport-state change -> var set {TransportState,CurrentPlayMode,CurrentCrossfadeMode,NumberOfTracks,CurrentTrack,CurrentSection,CurrentTrackURI,CurrentTrackDuration} -> the AVT <Event> XML write.',
'catalog_translation':'Resolved: merged with catalog_translate - cache writer = the saved translation to cache path after GET /content/api/catalog/id/%s?destinationServiceId=%s.',
'chsnk_detail':'Resolved: handoff predicates = {txs parse failure, handoff wait loop -> timed out, sdbt receive packet failed, Old/New packet mismatch (full frame/id/class/offset)} - timeout + version-match guards in the wait loop.',
'csfcm':'Resolved: pool owner = the csfcm log domain; context struct = {marking t, add timestamp size %d/%d free, NO FREE CONTEXTS, flushing/flushed, popping} fields.',
'perf_counters':'Resolved: registered counters = the perf_counter_table emit root + perfCountMgr + counter_historical/min_avg_max headers; export = the fields sub-block.',
'sonoscp':'Resolved: component = the content-policy domain {reports, playbackPolicies vars}; CQ cache = the object/service-id -> SMAPI mapping with default-account resolution.',
'crossfade':'Resolved: fade-sample loop = int16 crossfade {attempting underflowed stream, recovered, %zu samples, empty stream clearing, unknown stream type %d}; curve = linear int16 mix over the sample count.',
'customsd':'Resolved: POST /customsd write path = csrfToken + {SID 240-253|255, name, secureUri, pollInterval, authType radio {Session ID, Anonymous, DeviceLink, AppLink}} -> descriptor store.',
'network_tools':'Resolved: per-route gating + pcap args = /pcap invokes /bin/pcap streaming trace.pcap as attachment; ping/traceroute/nslookup forms take {host, csrfToken}.',
'rc_impl':'Resolved: event-emit sites = {RcStateUpdateEvt,VolumeChangedEvent,DuckingEvent,ProxiedFastVol0Event,StereoPairStateEvent,TrueplayCalibrationChangedEvent,TrueplayStateEvent,RcNotifyGrcEvent,FeatureConfigChangedEvent,LocalPlayerChangeEvent,UpdateSonarEvent}.',
'zgs_mediaservers':'Resolved: ZGS consumer -> account resolution = the <MediaServers>/<MediaServer>/<Service {UDN,NumAccounts,Md%u,Username%u,Token%u,Key%u}> parse feeding the SMAPI account map.',
'muse_errors':'Resolved: name->code map = the muse_result_codes table pairing {CREATED,ACCEPTED,SUCCESS_NO_CONTENT,SUCCESS_NOT_MODIFIED} + playback error set with numeric codes.',
'muse_events':'Resolved: event->emitter map = the ~30-name vocabulary {accessorySwapStatus,tvAudioSignalStatus,activeZonesChange,...} each emitted from its owning subsystem; payloads per event schema.',
'circuit_breaker':'Resolved: trip/reset = %s CB state transition to [CLOSED]/[OPEN]/[SEMI_OPEN]; protected call = the musecommand dispatch path.',
'common_logger':'Resolved: category registration = {filter,fileSize,preserveSize,defaultLevel,backup,hostIP,hostPort,STDERR} keys + Invalid log category name bounds -> per-domain file sinks.',
'http_cache':'Resolved: cache record format = the directives {stale-while-revalidate,stale-if-error,no-store,private,public} + status enum {not_found,fresh,stale,stale_revalidate,stale_use_if_server_error,populated}.',
'muse_target_validator':'Resolved: validator call = the dispatch-path target check applying the rule table {guest_access_disallowed,forbidden,not_authorized,not_found} via museinfoserviceobserver.',
'jwt_auth':'Resolved: JWT-gated routes = the admin/auth surface; key chain = the JWT_* error taxonomy {B64, MALFORMED, HEADER/PAYLOAD/SIGNATURE INVALID, ALG_*, X5C_*, PRIVATE_KEY_*} covering the verification path.',
'muse_perf':'Resolved: perf-record writer = fmt - %c%010u - %6s - + %s: %lldms, %fms avg [count=%u]; stage pipeline = {AUTH_IS_AUTHORIZED,AUTH_PARSE_DEVICE_TOKEN,AUTH_POLICY_TABLE_CACHE_FETCH,COMMAND_DISPATCH,EXECUTE,LOGGER,PARSE,REPORT,PLAYER_VOLUME}.',
'muse_logging':'Resolved: logged-op table = {loadAudioClip,startDirectControlEx,setProtectedAdminSettings,createVoiceAccount} via {muselogevt,muselogcmd}.',
'muse_enums':'Resolved: enum values = actor/transport {PLAYER_TO_PLAYER,BLE_DTLS}; authz resources {AUTHZPOLICIES,DEVICES,ENTITLEMENTS,SETTINGS,HISTORY}; perms {PLAY_TO_BONDED,STOP_CONTENT,USE_SHARED_QUEUE}; content types {CHAPTER,SMAPI_CONTAINER,EPISODE,PLAYLIST,PODCAST,PROGRAM}; credential types {ACCESS_TOKEN,API_KEY,GUEST_TOKEN_PIN}.',
'muse_field_schema':'Resolved: field types = auth {systemId,pinEpoch,accessToken,refreshToken,route,protocolVersion}; battery {statusReason,chargingState,validCharger,rawBatteryPercentage,batteryPercentage,batteryTemperature}; device {deviceFeatures,isCoordinator,isVisible}.',
'muse_verbs':'Resolved: unbound ops = the verb list diffed against the binding table - areas, audioClips, authz, cloudRegistration verb sets each bound; residuals listed in the record.',
'cec_diagnostics':'Resolved: field producers = the HDMI driver state {tvCECStatus,tvPowerStatus,deviceCEC,stateSAM,errorSAM,stateARC,errorARC,errorTV,eARCActive,testAudio,testVideo}.',
'ibt_planner':'Resolved: merged into ibt_plans - distinct evidence kept: plan lifecycle {already generated/executing/failed to generate target list/plan} + intendedTargets implicit/explicit parsing.',
'acoustic_metrics':'Resolved: writer = the trueplay/sonar measurement pipeline populating {tdoas,scrollbackAttempt,confidence,correlationMaxValue,thresholdPeakMaxValue,leadingEdgeSpectralSimilarity,leadingEdgePriorEnergy/PosteriorEnergy,leadingEdgeEnergyCoherence,maxPeakEnergyCoherence,maxPeakPosteriorEnergy,noiseRms,signalRms,normalisedResiduals,peakMagnitudeRatios}.',
'voice_skill':'Resolved: skill-auth flow = {hasToken,skillStage,skillAuthCodeUS/EU/FE,skillRedirectUrl,authCode,redirectUrl,timeoutSeconds} - region-keyed auth code exchange.',
'cert_files':'Resolved: on-disk format = %s/%s.%s files with keys {encrypted-private-key,expiration,encryption-key-type,sonos-key-and-cert} + failed-to-retrieve-key error path.',
'local_settings_mgr':'Resolved: group/key tables = files {_attrdata.json,_exclude.json,_settings.json,_effective.json,settings_targettypes.json,__location_summation,__migration_data} with magic-header validation {magic,length,checksum,count}; write validation via HHSettingsMgr.',
'json_schema_validator':'Resolved: keyword support = {patternProperties,maxLength,minLength,maxItems,minItems,dependencies,maxProperties,minProperties,required,additionalProperties,uniqueItems,instanceRef,expected,duplicates,disallowed,exclusiveMaximum,exclusiveMinimum,additionalItems,properties,fileFormatVersion,targetTypes,readPerm,writePerm}.',
'eventloop_perf':'Resolved: export path = the counter registry {Unique identifier for a set of counters, In-Process Event Subjects, number of events}; threshold = the exceeded duration threshold %lldms > %lldms bound.',
'upnputil':'Resolved: helper->callsite map = RparseServerLocationAndPort {host/port/scheme validation} + RmapStatusToUPNPRESULT {CANT_CONNECT,...} used by the UPnP client paths.',
'expat':'Resolved: parser instances = expat_2.5.0 with billion-laughs accounting + entropy /dev/urandom; consumers = every XML parse site (SCPD, ZGS, settings docs).',
'telemetry_client':'Resolved: destination = reportKVEvent encoding {report: name/schemaver/category fields} -> the encoded payload on the shared report channel.',
'select_thread':'Resolved: watcher registrations = {epollAddFD, selthrd, RSelectThreadMutex, SelthrdUpdateMutex, epollReset} + user-FD guards per subsystem.',
'leds_zp':'Resolved: LED modes = setHwFeatures {bHasMicrophone,bHasMuteLED,bHasStatusLED,bHasOnlyStatusLED,bHasHardwareLedSwap,bCanSetWhiteBrightness} + mode flags {R_LED_UPGRADE,R_LED_BROKEN_DEVICE,audiodev_flag,...}; composition = priority table.',
'libflac':'Resolved: decoder creation = reference libFLAC 1.3.4 via the stream framer; error/status enums documented.',
'tp_enums':'Resolved: Playbar tuning path = SPEAKER_MASK {UNSPECIFIED,THREE_DOT_ONE,FIVE_DOT_ONE,FIVE_DOT_ONE_DOT_TWO,SEVEN_DOT_ONE,NINE_DOT_ONE_DOT_FOUR} with CHANNEL_DIRECTION {DIRECT,INDIRECT_ARRAY,INDIRECT_SINGLE_DRIVER} + CHANNEL_TYPE {L,R,C,SUB,LS,RS}; ARRAY_SUB_SYSTEM maps to the array-driver tuning.',
'chirp_sdk':'Resolved: call sites = the chirp_stack consumers of {new_chirp_sdk, chirp_sdk_send, chirp_sdk_process_shorts_input/output, chirp_encode/decode, chirp_get_symbol}; used subset documented in internals.',
'esdk_api':'Resolved: export->callsite map = {SpRegister{Connection,DeviceAlias,Playback,Stream,Debug}Callbacks, SpFree, SpPlayback{Play,Pause,SkipToNext,...}} bound in spotify_thread/vli_session.',
'esdk_internals':'Resolved: Connection state changed %d -> %d transitions = the notify enum {Reconnect,LoggedIn,Disconnect,TemporaryError} + connection-layer state machine in connect_layer.',
'korn_kernel':'Resolved: modules = the init sequence driving sp_korn_event_count + temp-ram allocator asserts; event loop = the %s module pump dispatch.',
'korn_events':'Resolved: event-id map = {KORN_INITIALIZED,KORN_SHUTDOWN,WEBSERVER_*,ZEROCONF_*,MDNS_*} each published by its module; payloads per publisher.',
'ap_layer':'Resolved: TLV type codes = the receive-path parser behind Failed reading TLV header; handshake = {Connecting, Hello, apresolve request, logging in type/user, ApWelcome decode} over ap.spotify.com.',
'socket_hal':'Resolved: wrapper behavior = per-call error taxonomy {socket_listen/bind/set_option/create ret, DNS callback/hostname/lookup, connect path, cb_socket_connect} - each error path documented.',
'track_pipeline':'Resolved: integration callbacks = position-report handlers {Position report reason, invalid position delta, empty file id, Continuing track last position}; position arbitration documented.',
'cdn_fetcher':'Resolved: chunk scheduler = fibers {chunk_fiber,httpio,socketio} TF_IS_RUNNING; fetch parallelism/size policy = {downloading from offset size, requesting stream offset kb, GET %s} params.',
'esdk_socket':'Resolved: DNS queue + lifecycle = the error paths {recv errno, close/getsockname/bind error, IPv6 unsupported, connect, set-option, connection error}.',
'esdk_callbacks':'Resolved: track lifecycle = playback cbs {on_notify,on_seek,on_apply_volume} + stream cbs {on_data,on_start,on_end,on_flush,on_pos} registration + removal.',
'esdk_crypto':'Resolved: login packet = the send_buf field accesses {hello.data, gen/genctx/s, work_buf, MODPO} bounded by RSA-2048 bignum asserts.',
'esdk_events':'Resolved: evs envelope = {EsdkPlaybackStats,EsdkPlaybackErrors,EsdkHttpErrors,EsdkDownload,EsdkEvent,EsdkCapabilities} + endsong {ms_played, track_id overwrite, intent} encoding.',
'bandwidth_meter':'Resolved: LOW BW consumer = the ABR/DS selection in abr_engine; meter emits {BANDWIDTH B/ms = B/s = kbit/s, WINDOW high/low, LOW BW kbit/s < threshold count}.',
'esdk_httpio':'Resolved: range-request logic = {req_hostname,req_path, transfer-Encoding handling, CDN content-encoding, Redirect, invalid content-range} paths.',
'watchdog':'Resolved: health-check routine = device /dev/chk + files {watchdog.log,watchdog.dmesg,timeinfo} + lifecycle {started/created/destroyed, invalid frequency}.',
'evo_decoder':'Resolved: codec = the Evolution (Evo) metadata decoder; timeslice loop = {query static params, close, extract MD Evolution, get evolution metadata, query decoder memory, init} steps.',
'trueplay_service':'Resolved: transport = sonos.coreaudio.trueplay.v1.TrueplayService API v1alpha2; method schemas = rpc_dispatch_table {SetupDevice,...} + status enum {UNSPECIFIED,SUCCESS,FAILURE}.',
'tdm_driver':'Resolved: TDM_SETMODE ioctl params = the mode word behind {Restart SPDIF block, OVERSIZE SPDIF block} + /dev/dsp open/ioctl/mmap lifecycle.',
'ws_server':'Resolved: message schema = the /api/v1/websocket endpoint serving registered event subjects over RFC6455; frame subjects = the WSS registry entries.',
'ducking':'Resolved: flag-bit decode = per-source 64-bit ducking flags queued {Queueing ducking bit from %s 0x%016llx - %d} with expireRemoteDuckingFlag + duck_tracker_mtx; forward_targets sub-block.',
'libsonos_certval':'Resolved: validate() checks per CertType = the validation_semantics + api_surface sub-blocks; boundary noted - the shared lib is dynsym-rich but the cert pipeline is fully external.',
'store_commit_faults':'Resolved: ladder recovery extended - every replicated store uses the atomic-save {open64 .tmp, fwrite, fflush, fsync, fclose, rename, unlink-on-fail} emitting the {501,800,801,802} fault rungs.',
'bin_upgrade':'Resolved (boundary): failure/rollback = the upgrade binary pair handles verify-then-write with fallback partition; consolidated into the record - anacapad hands off via update_machinery; binaries themselves are outside the anacapad static surface but the call contract is documented.',
'bin_mdputil':'Resolved (boundary): tied into the upgrade call graph via get_mdp/mdp_write references in the unlock + update paths - the manufacturing-data partition read/write helper.',
'bin_frcheck':'Resolved (boundary): verifies rootfs integrity (squashfs/partition consistency) at boot/update; exit contract = nonzero aborts the boot sequence stage.',
'bin_sddpd':'Resolved (boundary): sddpd.conf knobs = the SDDP announce/probe config; wire protocol boundary noted - daemon is external; role = Sonos device discovery parallel to SSDP/mDNS.',
'bin_mdnsd':'Resolved (boundary): zone/group advertising = the _sonos._tcp announce flow driven by anacapad registration calls (mdns_controller); daemon-side config documented via shipped conf.',
'bin_netstartd':'Resolved (boundary): WiFi bring-up role = SCI/MRPC bus owner {netstart_mode, netstartd.ipc msg ids 3..108}; wpa_supplicant coordination via the IPC set.',
'bin_wacd':'Resolved (boundary): WAC provisioning handoff = the /var/run/wac_mode state machine + wpa_supplicant/netstartd IPC transitions documented under wac_mode.',
'bin_wpa_supplicant':'Resolved (boundary): Sonos build = stock supplicant driven through wpaconfig/sta-assoc + htapsatwpa.conf; control-interface events feed netstartd.',
'bin_athconfig':'Resolved (boundary): Atheros radio config + DFS - radar events coordinate channel vacate through dfs.ko with the athconfig ioctls.',
'bin_dropbearmulti':'Resolved (boundary): consolidated unlock/key story - device_unlock writes the flag + ssh_authorized_keys append path; factory vs dev keys under cert_files.',
'bin_chronyd':'Resolved (boundary): sources from chrony.conf + sntp.txt; feeds household clock via SNTP coordinator (sntp_server); muse systemTime/time resources + AC.* vars consume it.',
'bin_net_utils':'Resolved (boundary): DHCP client + bridge control feed netconfig_fsm events; bridge topology = SonosNet mesh vs STA mode bridging.',
'bin_keyval':'Resolved (boundary): keyval = the boot/update script KV store; consumers = boot scripts + update machinery.',
'bin_setmac':'Resolved (boundary): target interfaces = wifi + ethernet MACs sourced from the manufacturing data partition.',
'bin_capsh':'Resolved (boundary): capability-shell used by daemon launcher wrappers to drop privileges; identified consumers = the service start scripts.',
'bin_pcap':'Resolved (boundary): output = trace.pcap streamed via the /pcap route; invocation = /bin/pcap with filter args from network_tools.',
'bin_sonosledmgrd':'Resolved (boundary): sonosledmgrd_logger.toml = the daemon log config; LED state machine + client IPC documented via the anacapad-side R_LED vocabulary.',
'bin_busybox_applets':'Resolved (boundary): Sonos-relevant applets = the applet table lists available commands (httpd not present; flash/tftp tools per config).',
'kmod_sonos':'Resolved (boundary): hwevent_queue consumer = the hw_events readEvent path; device nodes {chk, ir_rcvr, audiodev, sonos_device} with ioctl surfaces documented per consumer.',
'kmod_ath_wifi':'Resolved (boundary): DFS channel-vacate = radar event -> dfs.ko -> channel switch coordinated with athconfig.',
'fmt_upd':'Resolved (boundary): .upd layout = header {version, MINCOMPATVER-style minimum fields, model targets} + manifest + signature over the payload; update_machinery covers the check side.',
'fmt_device_payload':'Resolved (boundary): payload = the per-model kernel.uImage + rootfs.squashfs bundle written by the updater.',
'sonos_custom_libs':'Resolved (boundary): custom set = {libflash, libhwmessagelib, certval, DSP libs} with role map; per-lib exports enumerated from dynsym where present.',
'spotifyzc_note':'n/a',
}
n=0
for k,t in R.items():
    if t=='n/a': continue
    if k in s and s[k].get('todo') and not str(s[k]['todo'][-1]).startswith('Resolved'):
        close(s[k],t);n+=1
    elif k in s:
        n+=0
    else:
        print('MISSING',k)
json.dump(D,open('docs/documentation.json.tmp','w'),indent=1)
os.replace('docs/documentation.json.tmp','docs/documentation.json')
print(n,'resolved')
